export const SET_IS_LOADING = 'SET_IS_LOADING';
export const REQUEST_SEARCH_ID = 'REQUEST_SEARCH_ID';
export const SET_SEARCH_ID = 'SET_SEARCH_ID';
export const ADD_FOUND_TICKETS = 'ADD_FOUND_TICKETS';
export const LOAD_TICKETS_PORTION = 'LOAD_TICKETS_PORTION';
export const SET_STOPS_FILTER = 'SET_STOPS_FILTER';
export const SET_ORDER_BY = 'SET_ORDER_BY';
